#!/bin/bash

ee=1e-6
z=0.01

for ee in 1e-3 1e-6 1e-9 ; do
for ngp in 4 8 12 16 20 ; do
    outputa=adaptive-t-error-${ee}-${ngp}.dat
    outputd=duffy-t-error-${ee}-${ngp}.dat

    rm -f ${outputa} ${outputd}
    for t in 30 60 90 120 150 ; do
	rm -f angle-test.dat
	x=`echo s\(${t}*3.14159/180\) | bc -l`
	y=`echo 1.0-c\(${t}*3.14159/180\) | bc -l`
	echo 0 0 ${z} >> angle-test.dat
	echo 0 0 0 >> angle-test.dat
	echo 0 1 0 >> angle-test.dat
	echo ${x} ${y} 0 >> angle-test.dat
	../tqtest -p ${ngp} -r ${ngp} -t ${ngp} -T singular -N 3 \
		  -d 8 -e ${ee} -i angle-test.dat -z ${z} > errors.dat 2> log
	((np = ${ngp}*${ngp}*${ngp}))
	lnp=`echo l\(${np}\)/l\(10\) | bc -l`
	erra=`grep errors log | cut -d " " -f 3`
	errd=`grep errors log | cut -d " " -f 4`
	echo ${t} ${lnp} >> ${outputd}
	depth=`grep depth log | cut -d " " -f 3`
	lnp=`echo l\(\(4^${depth}-1\)/3*${np}\)/l\(10\) | bc -l`	
	echo ${t} ${lnp} >> ${outputa}
    done
done
done
