#!/bin/bash

ee=1e-6
z=0.0025

for ee in 1e-3 1e-6 1e-9 ; do
for ngp in 4 8 12 16 20 ; do
    outputa=adaptive-a-error-${ee}-${ngp}.dat
    outputd=duffy-a-error-${ee}-${ngp}.dat

    rm -f ${outputa} ${outputd}
    for a in 1 2 3 4 5 6 7 8 9 10 ; do
	rm -f aspect-test.dat
	echo 0 0 ${z} >> aspect-test.dat
	echo 0 0 0 >> aspect-test.dat
	echo 0 1 0 >> aspect-test.dat
	echo ${a} 1 0 >> aspect-test.dat

	../tqtest -p ${ngp} -r ${ngp} -t ${ngp} -T singular -N 3 \
		  -d 8 -e ${ee} -i aspect-test.dat -z ${z} > errors.dat 2> log
	((np = ${ngp}*${ngp}*${ngp}))
	lnp=`echo l\(${np}\)/l\(10\) | bc -l`
	erra=`grep errors log | cut -d " " -f 3`
	errd=`grep errors log | cut -d " " -f 4`
	echo ${a} ${lnp} >> ${outputd}
	depth=`grep depth log | cut -d " " -f 3`
	lnp=`echo l\(\(4^${depth}-1\)/3*${np}\)/l\(10\) | bc -l`	
	echo ${a} ${lnp} >> ${outputa}
    done
done
done
