#!/bin/bash

z=0.1
for t in 30 60 90 120 150 ; do
    outputb=basic-angle-${t}.dat
    outputa=adaptive-angle-${t}.dat
    outputd=duffy-angle-${t}.dat

    rm -f angle-test.dat
    x=`echo s\(${t}*3.14159/180\) | bc -l`
    y=`echo 1.0-c\(${t}*3.14159/180\) | bc -l`
    echo 0 0 ${z} >> angle-test.dat
    echo 0 0 0 >> angle-test.dat
    echo 0 1 0 >> angle-test.dat
    echo ${x} ${y} 0 >> angle-test.dat
    
    rm -f ${outputa} ${outputb} ${outputd}
    for ngp in 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 ; do
	../tqtest -p ${ngp} -r ${ngp} -t ${ngp} -T singular -N 3 \
		  -d 8 -e 1e-12 -i angle-test.dat -z ${z} > errors.dat 2> log
	((np = ${ngp}*${ngp}*${ngp}))
	lnp=`echo l\(${np}\)/l\(10\) | bc -l`
	errb=`grep errors log | cut -d " " -f 2`
	erra=`grep errors log | cut -d " " -f 3`
	errd=`grep errors log | cut -d " " -f 4`
	depth=`grep depth log | cut -d " " -f 3`
	echo ${lnp} ${erra} ${depth} >> ${outputa}
	echo ${lnp} ${errb} >> ${outputb}
	echo ${lnp} ${errd} >> ${outputd}
    done
done
