#!/bin/bash

z=0.1
for a in 1 3 5 10 ; do
    outputb=basic-aspect-${a}.dat
    outputa=adaptive-aspect-${a}.dat
    outputd=duffy-aspect-${a}.dat

    rm -f aspect-test.dat
    echo 0 0 ${z} >> aspect-test.dat
    echo 0 0 0 >> aspect-test.dat
    echo 0 1 0 >> aspect-test.dat
    echo ${a} 1 0 >> aspect-test.dat
    
    rm -f ${outputa} ${outputb} ${outputd}
    for ngp in 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 ; do
	../tqtest -p ${ngp} -r ${ngp} -t ${ngp} -T singular -N 3 \
		  -d 8 -e 1e-6 -i aspect-test.dat -z ${z} > errors.dat 2> log
	((np = ${ngp}*${ngp}*${ngp}))
	lnp=`echo l\(${np}\)/l\(10\) | bc -l`
	errb=`grep errors log | cut -d " " -f 2`
	erra=`grep errors log | cut -d " " -f 3`
	errd=`grep errors log | cut -d " " -f 4`
	depth=`grep depth log | cut -d " " -f 3`
	echo ${lnp} ${erra} ${depth} >> ${outputa}
	echo ${lnp} ${errb} >> ${outputb}
	echo ${lnp} ${errd} >> ${outputd}
    done
done
